### ISSUE TITLE
Depreciation warning

### ISSUE THREAD

**Issue by adityabandla** [lozuponelab/SCNIC#11]
Installed SCNIC through conda, but I get the following warning when trying to run the python script

```
/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47:
DeprecationWarning: the imp module is deprecated in favour of importlib; 
see the module's documentation for alternative uses
import imp

**Comment by shafferm** [comment]
Thanks for letting me know about this. You can just ignore it. Upgrading to a newer version of scikit-learn in the next release should make this go away.
