### ISSUE TITLE
between_correls() parameter doesn't match with SCNIC_analysis.py script

### ISSUE THREAD

**Issue by JTFouquier** [lozuponelab/SCNIC#15]
Hi Mike,

There's an issue with the max_p and min_p parameters. I modified the parameter name in the pprimary SCNIC_analysis.py Python script to solve the issue. I think this should be checked in the docs and other releases. 

```
SCNIC_analysis.py between -1 microbe-modules-output_r35/collapsed.biom -2 gene-modules-output_r35/collapsed.biom -o module-module-between/ -m spearman
Traceback (most recent call last):
  File "/Users/jenniferfouquier/anaconda3/envs/SCNIC/bin/SCNIC_analysis.py", line 81, in <module>
    main()
  File "/Users/jenniferfouquier/anaconda3/envs/SCNIC/bin/SCNIC_analysis.py", line 77, in main
    args.func(**args_dict)
TypeError: between_correls() got an unexpected keyword argument 'max_p'
```

**Comment by Candice-Q** [comment]
I am getting the same error message. How did you solve this?

**Comment by brbergamo** [comment]
I'm having this error too! Does anyone know how to solve it?

**Comment by timyerg** [comment]
Workaround:
To solve this issue, search for 'SCNIC_analysis.py' in bin directory of your environment and replace 'max_p' with 'min_p' at line 66

**Comment by ETaSky** [comment]
> 

So the issue is the parameter name in the `SCNIC/between_correls.py`, which SCNIC_analysis.py would import, is `max_p` instead of `min_p`. So you need to replace the `min_p` with `max_p` at line 66 of SCNIC_analysis.py (not the other way round), and use `--max_p` in the cli.

**Comment by sterrettJD** [comment]
Hi folks, it looks like `between_correls.py` never implemented p-value based filtering. I've updated the arguments as @ETaSky suggested, and now SCNIC raises a more informative error for this argument being passed, but if anybody wants to open a pull request to allow it to do so, please feel free to open a pull request.

@JTFouquier lmk if you wanna chat about this at any point
