### ISSUE TITLE
Conda install not working

### ISSUE THREAD

**Issue by afvrbanac** [lozuponelab/SCNIC#18]
Hello, just tried to install both on my local machine (mac) and on a linux aws machine. Both have miniconda with the bioconda channel added.

Running:
conda create -n SCNIC python=3 scnic

Gives the error:
Package python conflicts for:
scnic -> python[version='>=3']
python=3
scnic -> biom-format -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|3.4.*|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6|>=3.5']

**Comment by afvrbanac** [comment]
Was able to install by creating an conda env with only python 3, installing numpy and cython in that env (pip install of SCNIC errored until these were installed), then pip installing SCNIC

**Comment by kthurimella** [comment]
Thanks for raising the issue @afvrbanac, it looks like the conda install isn't working but the pip install in general should work, even if you install it within a virtual env that you create.
