### ISSUE TITLE
fastspar

### ISSUE THREAD

**Issue by lmsolden** [lozuponelab/SCNIC#6]
Can you update your readme file to include that fastspar is required for use? We could not run SCNIC without it and were not sure why it wasn't working.

Thanks

**Comment by shafferm** [comment]
I have updated the readme to included updated installation instructions including the recommendation of installing fastspar via conda. I'm hoping that within the next week SCNIC will be available via conda and make these problems go away! Thanks for pointing out this deficiency in the readme!
