### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by lizbent** [lozuponelab/SCNIC#9]
Hi, I get error messages when:

1.  I attempt to use the -m sparcc option: Input triggered condition to perform clr correlation, this is not yet implemented (then a traceback to SCNIC_analysis.py line 73) Command: SCNIC_analysis.py within -i AAAA-T-feature-table.biom -o AAAA-T-output/ -m sparcc --sparcc_filter --sparcc_p 1000

2. I can use the -m pearson option and get p-values just fine, but when I attempt to use modules and the -min_p option, it crashes again (traceback to SCNIC_analysis.py line 73 again) Command: SCNIC_analysis.py modules -i AAAA-T-output/correls.txt -o AAAA-T-pearson-modules/ --min_p .05 --table AAAA-T-feature-table.biom

It works okay with --min_r .35, so for now I am using that. 

Also, shouldn't it be max_p? You don't want to use high p values. 

I installed SCNIC via conda- should I also install something else to get item 1 to work?

**Comment by shafferm** [comment]
Hello,

1. This usually occurs when sample size is small. This was an option in an earlier sparCC implementation which is not available in fastspar. I'd recommend always having more than 15 samples to be able to reliably calculate correlations.

2. This is a bug that I have not pushed to conda or pip yet. It will be pushed soon. And you are right that it should be max_p.
